apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-python-api
  template:
    metadata:
      labels:
        app: simple-python-api
    spec:
      containers:
      - name: simple-python-api
        image: diegodejesus/simple-python-api:28785d1aff1b7d2ea08f042e9508daa1fae41bb1
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: simple-python-api
spec:
  selector:
    app: simple-python-api
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort

